# Generated by Django 5.0.3 on 2024-05-14 18:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_manufacturer_alter_attribute_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttributeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
            ],
            options={
                'verbose_name': 'Тип данных характеристик',
                'verbose_name_plural': 'Типы данных характеристик',
            },
        ),
        migrations.AddField(
            model_name='attribute',
            name='unit_of_measurement',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Единица измерения'),
        ),
        migrations.AlterField(
            model_name='attribute',
            name='data_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.attributetype'),
        ),
    ]
