# Generated by Django 5.0.3 on 2024-05-19 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_favorites'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favorites',
            options={'verbose_name': 'Избранное', 'verbose_name_plural': 'Избранное'},
        ),
    ]
